### ISSUE TITLE
Create Quotes by me Screen

### ISSUE THREAD

**Issue by sahibul-nf** [sahibul-nf/quotes_app#8]
### 📝 Description:
Create **Quotes by me Screen** like the UI design below!
**Branch name:** feat-8/ui-quotes-by-me

**Contribute Guideline:**
https://vine-roarer-af1.notion.site/Contribute-Guideline-Quotes-App-Flutter-6563ccc683eb497f806341713c171eff

**UI Design:**
https://app.visily.ai/projects/cd719b2e-1d58-4329-8b15-791e21917593/boards/473019/elements/160921287

**Preview Design:**
![Image](https://github.com/sahibul-nf/quotes_app/assets/67043376/84712765-9037-4f6d-85f0-062a7fcdc784)

**Comment by JundyMardhatillah** [comment]
I'm happy to be here, it turns out I'll be solving this issue. Let's get started!
